CITY_CONFIGS_26 = {
    "sao_paulo": {
        "display_name": "São Paulo",
        "polygon_city_name": "São Paulo",
        "polygon_city_column": "nm_mun",
        "slug": "sao_paulo",
    },
    "rio": {
        "display_name": "Rio de Janeiro",
        "polygon_city_name": "Rio de Janeiro",
        "polygon_city_column": "nm_mun",
        "slug": "rio_de_janeiro",
    },
    "brasilia": {
        "display_name": "Brasília",
        "polygon_city_name": "Brasília",
        "polygon_city_column": "nm_mun",
        "slug": "brasilia",
    },
    "fortaleza": {
        "display_name": "Fortaleza",
        "polygon_city_name": "Fortaleza",
        "polygon_city_column": "nm_mun",
        "slug": "fortaleza",
    },
    "salvador": {
        "display_name": "Salvador",
        "polygon_city_name": "Salvador",
        "polygon_city_column": "nm_mun",
        "slug": "salvador",
    },
    "belo_horizonte": {
        "display_name": "Belo Horizonte",
        "polygon_city_name": "Belo Horizonte",
        "polygon_city_column": "nm_mun",
        "slug": "belo_horizonte",
    },
    "manaus": {
        "display_name": "Manaus",
        "polygon_city_name": "Manaus",
        "polygon_city_column": "nm_mun",
        "slug": "manaus",
    },
    "curitiba": {
        "display_name": "Curitiba",
        "polygon_city_name": "Curitiba",
        "polygon_city_column": "nm_mun",
        "slug": "curitiba",
    },
    "recife": {
        "display_name": "Recife",
        "polygon_city_name": "Recife",
        "polygon_city_column": "nm_mun",
        "slug": "recife",
    },
    "goiania": {
        "display_name": "Goiânia",
        "polygon_city_name": "Goiânia",
        "polygon_city_column": "nm_mun",
        "slug": "goiania",
    },
    "belem": {
        "display_name": "Belém",
        "polygon_city_name": "Belém",
        "polygon_city_column": "nm_mun",
        "slug": "belem",
    },
    "porto_alegre": {
        "display_name": "Porto Alegre",
        "polygon_city_name": "Porto Alegre",
        "polygon_city_column": "nm_mun",
        "slug": "porto_alegre",
    },
    "guarulhos": {
        "display_name": "Guarulhos",
        "polygon_city_name": "Guarulhos",
        "polygon_city_column": "nm_mun",
        "slug": "guarulhos",
    },
    "campinas": {
        "display_name": "Campinas",
        "polygon_city_name": "Campinas",
        "polygon_city_column": "nm_mun",
        "slug": "campinas",
    },
    "sao_luis": {
        "display_name": "São Luís",
        "polygon_city_name": "São Luís",
        "polygon_city_column": "nm_mun",
        "slug": "sao_luis",
    },
    "maceio": {
        "display_name": "Maceió",
        "polygon_city_name": "Maceió",
        "polygon_city_column": "nm_mun",
        "slug": "maceio",
    },
    "campo_grande": {
        "display_name": "Campo Grande",
        "polygon_city_name": "Campo Grande",
        "polygon_city_column": "nm_mun",
        "slug": "campo_grande",
    },
    "sao_goncalo": {
        "display_name": "São Gonçalo",
        "polygon_city_name": "São Gonçalo",
        "polygon_city_column": "nm_mun",
        "slug": "sao_goncalo",
    },
    "teresina": {
        "display_name": "Teresina",
        "polygon_city_name": "Teresina",
        "polygon_city_column": "nm_mun",
        "slug": "teresina",
    },
    "joao_pessoa": {
        "display_name": "João Pessoa",
        "polygon_city_name": "João Pessoa",
        "polygon_city_column": "nm_mun",
        "slug": "joao_pessoa",
    },
    "duque_de_caxias": {
        "display_name": "Duque de Caxias",
        "polygon_city_name": "Duque de Caxias",
        "polygon_city_column": "nm_mun",
        "slug": "duque_de_caxias",
    },
    "nova_iguacu": {
        "display_name": "Nova Iguaçu",
        "polygon_city_name": "Nova Iguaçu",
        "polygon_city_column": "nm_mun",
        "slug": "nova_iguacu",
    },
    "sao_bernardo_do_campo": {
        "display_name": "São Bernardo do Campo",
        "polygon_city_name": "São Bernardo do Campo",
        "polygon_city_column": "nm_mun",
        "slug": "sao_bernardo_do_campo",
    },
    "natal": {
        "display_name": "Natal",
        "polygon_city_name": "Natal",
        "polygon_city_column": "nm_mun",
        "slug": "natal",
    },
    "santo_andre": {
        "display_name": "Santo André",
        "polygon_city_name": "Santo André",
        "polygon_city_column": "nm_mun",
        "slug": "santo_andre",
    },
    "sorocaba": {
        "display_name": "Sorocaba",
        "polygon_city_name": "Sorocaba",
        "polygon_city_column": "nm_mun",
        "slug": "sorocaba",
    },
}